### ISSUE TITLE
struct.error: short format requires (-0x7fff - 1) <= number <= 0x7fff

### ISSUE THREAD

**Issue by Grace-TL** [Princeton-Cabernet/BeauCoup#2]
There is another issue here. When I run the python simulator, it reports errors as follows.

`$ python3 py/simulator.py --seed=1 test/IR.json test/caida0.npy test/reports.npz`
`Traceback (most recent call last):
  File "py/simulator.py", line 34, in <module>
    lib_eval.simulate_run(args.npy_filename, args.out_filename, IR, args.seed, debug=args.verbose)
  File "/home/ltang/Workspace/research/store/BeauCoup/py/core/lib_eval.py", line 189, in simulate_run
    val=h_compute[j](Trace[i])
  File "/home/ltang/Workspace/research/store/BeauCoup/py/core/lib_eval.py", line 108, in <lambda>
    return lambda val:pull_pack_and_compute(list_indexes,val, mask, seedbytes, Pack_formatstring)
  File "/home/ltang/Workspace/research/store/BeauCoup/py/core/lib_eval.py", line 105, in pull_pack_and_compute
    base+=struct.pack(Pack_formatstring[i],value_list[i])
struct.error: short format requires (-0x7fff - 1) <= number <= 0x7fff`

The IR.json is compiled from the query_examples.yaml file in BeauCoup folder.

**Comment by chenxiaoqino** [comment]
There's a mismatch between unsigned/signed format, I have made it consistent. Thanks for reporting.
